# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-06-17 20:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mediaportalapp', '0004_useraccount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='favorite_articles',
            field=models.ManyToManyField(blank=True, to='mediaportalapp.Article'),
        ),
    ]
